/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stu_wujian_kwsdemo_utils_KWSKERNEL */

#ifndef _Included_com_stu_wujian_kwsdemo_utils_KWSKERNEL
#define _Included_com_stu_wujian_kwsdemo_utils_KWSKERNEL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stu_wujian_kwsdemo_utils_KWSKERNEL
 * Method:    initSystem
 * Signature: (Landroid/content/res/AssetManager;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_stu_wujian_kwsdemo_utils_KWSKERNEL_initSystem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_stu_wujian_kwsdemo_utils_KWSKERNEL
 * Method:    waveToFBank
 * Signature: ([S)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_stu_wujian_kwsdemo_utils_KWSKERNEL_waveToFBank
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_stu_wujian_kwsdemo_utils_KWSKERNEL
 * Method:    predictClass
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_stu_wujian_kwsdemo_utils_KWSKERNEL_predictClass
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_stu_wujian_kwsdemo_utils_KWSKERNEL
 * Method:    freeSystem
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_stu_wujian_kwsdemo_utils_KWSKERNEL_freeSystem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
